name: Ansible Copy File

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  ansible-copy-job:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose a Python version compatible with Ansible

    - name: Install Ansible
      run: |
        pip install ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i localhost, -c local ansible/copy-file.yml
      env:
        SOURCE_FOLDER: "path/to/source"
        DESTINATION_FOLDER: "path/to/destination"
